# Generated by Django 5.0 on 2023-12-17 11:39

import comptes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email1',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email2',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email3',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email4',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email5',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='fonction',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='medium',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='phone1',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='phone2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='phone3',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='phone4',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='phone5',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_couverture',
            field=models.ImageField(blank=True, null=True, upload_to=comptes.models.user_cover_photo_path),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='pinterest',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='quora',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='reddit',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='siteweb',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='snapchat',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='whatsapp_business',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='x',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
