# Generated by Django 5.0 on 2023-12-17 12:14

import comptes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_utilisateur_adresse_utilisateur_email1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email1',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='fonction',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='phone1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_couverture',
            field=models.ImageField(default='', upload_to=comptes.models.user_cover_photo_path),
            preserve_default=False,
        ),
    ]
