# Generated by Django 5.0 on 2023-12-29 23:45

import comptes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_alter_utilisateur_adresse_alter_utilisateur_email1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo_profile',
            field=models.ImageField(default='photos_profile/default.png', upload_to=comptes.models.user_profile_photo_path),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_couverture',
            field=models.ImageField(default='photos_couv/default.jpg', upload_to=comptes.models.user_cover_photo_path),
        ),
    ]
