# Generated by Django 5.0 on 2023-12-30 00:23

import comptes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_utilisateur_photo_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_couverture',
            field=models.ImageField(blank=True, null=True, upload_to=comptes.models.user_cover_photo_path),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profile',
            field=models.ImageField(upload_to=comptes.models.user_profile_photo_path),
        ),
    ]
