# Generated by Django 5.0 on 2023-12-30 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_alter_utilisateur_photo_couverture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
