# Generated by Django 5.0 on 2023-12-31 08:17

import comptes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_alter_utilisateur_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='lien_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_couverture',
            field=models.ImageField(blank=True, default='photos_couv/default.jpg', null=True, upload_to=comptes.models.user_cover_photo_path),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profile',
            field=models.ImageField(default='photos_profile/default.png', upload_to=comptes.models.user_profile_photo_path),
        ),
    ]
